"""
png2c.py -- embed the built-in avatar PNGs into a C++ header (PROGMEM byte
arrays) so the headless web UI can serve them straight from firmware flash,
with no SPIFFS data upload required.

Reads 1.png .. 15.png from this folder and writes src/Services/AvatarAssets.h.
Avatar web index 0..14 maps to file (index+1).png, matching handleAvatar().

Run from the repo root (or anywhere -- paths are resolved relative to this
file):  python data/Avatars/large/png2c.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "..", "src", "Services", "AvatarAssets.h"))
COUNT = 15


def emit_array(name, data):
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("\t" + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    blobs = []
    for n in range(1, COUNT + 1):
        path = os.path.join(HERE, f"{n}.png")
        with open(path, "rb") as f:
            blobs.append(f.read())

    out = []
    out.append("#ifndef CHATTER_FIRMWARE_AVATARASSETS_H")
    out.append("#define CHATTER_FIRMWARE_AVATARASSETS_H")
    out.append("")
    out.append("#include <Arduino.h>")
    out.append("")
    out.append("// Auto-generated by data/Avatars/large/png2c.py -- do not edit by hand.")
    out.append("// The 15 built-in avatar PNGs, embedded in flash so the headless web UI can")
    out.append("// serve them with NO SPIFFS data upload (Arduino IDE 2.x has no SPIFFS")
    out.append("// uploader for this board, which made the separate storage flash a recurring")
    out.append("// failure point). Web avatar index 0..14 -> (index+1).png.")
    out.append("")
    for i, data in enumerate(blobs):
        out.append(emit_array(f"Avatar{i}_png", data))
        out.append("")

    ptrs = ", ".join(f"Avatar{i}_png" for i in range(COUNT))
    lens = ", ".join(str(len(b)) for b in blobs)
    out.append("// Pointer/length tables kept in RAM (90 bytes total); they index into the")
    out.append("// PROGMEM blobs above.")
    out.append(f"const uint8_t* const AvatarPng[{COUNT}] = {{ {ptrs} }};")
    out.append(f"const uint16_t AvatarPngLen[{COUNT}] = {{ {lens} }};")
    out.append("")
    out.append("#endif //CHATTER_FIRMWARE_AVATARASSETS_H")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(out))

    total = sum(len(b) for b in blobs)
    print(f"Wrote {OUT}")
    print(f"{COUNT} avatars, {total} bytes embedded ({total/1024:.1f} KB of flash)")


if __name__ == "__main__":
    main()
