#ifndef CHATTER_FIRMWARE_T9DICT_H
#define CHATTER_FIRMWARE_T9DICT_H

#include <stdint.h>
#include <string>
#include <vector>
#include <utility>

/**
 * Read-only lookup over the frequency trie generated by tools/gen_t9_dict.py
 * and embedded in src/t9_dict.cpp (t9DictData).
 *
 * The trie is a *character* trie: each edge is a letter, so a word is recovered
 * by walking the path from the root. A T9 lookup follows, at each step, every
 * child whose letter belongs to the typed digit's letter set.
 *
 * Matching is PREDICTIVE (prefix-based): getMatches() returns every dictionary
 * word whose T9 encoding *starts with* the typed digits, ranked by frequency.
 * This drives the grey "predicted completion" UX. See the note in
 * implementation_plan.md (item K) about the exact-length-vs-prefix decision.
 */
class T9Dict {
public:
	// Mirrors the 8-byte on-flash layout exactly (see gen_t9_dict.py).
	struct __attribute__((packed)) TrieNode {
		char     character;          // 'a'..'z', or 0 for the root
		uint8_t  child_count;
		uint16_t weight;             // word frequency weight, 0 if not a word-end
		uint16_t max_weight;         // max weight anywhere in this subtree
		uint16_t first_child_index;  // BFS index of first child, 0 if leaf
	};

	// Point the lookup at the embedded blob. Safe to call repeatedly; getMatches
	// also lazy-initialises, so an explicit call is optional but cheap.
	static void init();

	// Words whose T9 encoding starts with `digits`, sorted by weight descending,
	// capped at `maxResults`. Empty when `digits` is not a valid prefix of any
	// word (the caller uses this to drive the invalid-key beep).
	static std::vector<std::pair<std::string, uint16_t>> getMatches(
			const std::string& digits, size_t maxResults = 16);

private:
	static const TrieNode* nodes;   // first node (root) of the trie
	static uint16_t nodeCount;

	static const char* digitLetters(char digit);

	// Phase 1: walk the digit path. Phase 2 (collectSubtree): gather every word
	// below the reached node, since all of them share the typed prefix.
	static void descend(uint16_t idx, const std::string& digits, size_t depth,
						 std::string& prefix,
						 std::vector<std::pair<std::string, uint16_t>>& out);
	static void collectSubtree(uint16_t idx, std::string& prefix,
							   std::vector<std::pair<std::string, uint16_t>>& out);
};

#endif //CHATTER_FIRMWARE_T9DICT_H
