#!/usr/bin/env python3
"""
gen_t9_dict.py
--------------
Reads tools/xxxxx.txt (one word per line, most-frequent first),
builds a sorted flat-array T9 dictionary, and emits:
  src/t9_dict.bin   – binary lookup table
  src/t9_dict.h     – C header with embedded array + constants

Binary layout
─────────────
[0..1]  uint16_t  entry_count        – number of (digits, offset) pairs
[2..3]  uint16_t  string_table_size  – byte length of string table
[4..]   entry_count × 10 bytes each:
            uint64_t  digits          (8 bytes, little-endian)
            uint16_t  word_offset     (2 bytes, little-endian, index into string table)
[4 + entry_count*10 ..]
        null-terminated strings, concatenated  (string table)

Lookup is O(log n) binary search on the digits field.
Words sharing the same digit sequence are contiguous, ordered
by frequency rank (lowest index = most frequent).
"""

import struct
import sys
import os
from pathlib import Path

# ── Phone key mapping -

CHAR_TO_DIGIT = {}
_mapping = {
    '2': 'abc',
    '3': 'def',
    '4': 'ghi',
    '5': 'jkl',
    '6': 'mno',
    '7': 'pqrs',
    '8': 'tuv',
    '9': 'wxyz',
}
for digit, letters in _mapping.items():
    for ch in letters:
        CHAR_TO_DIGIT[ch] = digit


def word_to_digits(word: str) -> str | None:
    """Return the T9 digit string for *word*, or None if any char is unmappable."""
    result = []
    for ch in word.lower():
        d = CHAR_TO_DIGIT.get(ch)
        if d is None:
            return None        # skip words with apostrophes, hyphens, etc.
        result.append(d)
    return ''.join(result)


def digits_to_int(digits: str) -> int:
    """Pack a digit string into a uint64 for fast integer comparison."""
    return int(digits) if digits else 0


# ── Load word list -────

def load_words(path: str) -> list[str]:
    words = []
    seen = set()
    with open(path, encoding='utf-8') as f:
        for line in f:
            word = line.strip().lower()
            if not word or any(ch < 'a' or ch > 'z' for ch in word):
                continue
            if word in seen:
                continue
            seen.add(word)
            words.append(word)
    return words


# ── Build entry table -

def build_entries(words: list[str]):
    """
    Returns (entries, string_table_bytes) where entries is a list of
    (digits_int: int, word_offset: int) sorted by (digits_int, freq_rank).
    freq_rank is the original position in *words* (0 = most frequent).
    """
    # Build string table first so we can record byte offsets
    string_table = bytearray()
    word_offsets: dict[str, int] = {}   # word → byte offset in string table

    for word in words:
        if word not in word_offsets:
            word_offsets[word] = len(string_table)
            string_table.extend(word.encode('ascii'))
            string_table.append(0)          # null terminator

    # Build unsorted entries; keep freq_rank for stable sort tiebreak
    raw: list[tuple[int, int, int]] = []   # (digits_int, freq_rank, word_offset)
    skipped = []

    for rank, word in enumerate(words):
        digits = word_to_digits(word)
        if digits is None:
            skipped.append(word)
            continue
        raw.append((digits_to_int(digits), rank, word_offsets[word]))

    if skipped:
        print(f"  Skipped {len(skipped)} words with unmappable characters: "
              f"{skipped[:8]}{'…' if len(skipped) > 8 else ''}")

    # Sort by digit key, then by frequency rank (most frequent first within group)
    raw.sort(key=lambda e: (e[0], e[1]))

    # Strip the rank now that ordering is baked in
    entries = [(digits_int, word_offset) for digits_int, _, word_offset in raw]

    return entries, bytes(string_table)


# ── Serialise -────────

ENTRY_STRUCT = struct.Struct('<QH')     # uint64_t digits, uint16_t word_offset
HEADER_STRUCT = struct.Struct('<HH')    # uint16_t entry_count, uint16_t string_table_size
ENTRY_SIZE = ENTRY_STRUCT.size          # 10 bytes

assert ENTRY_SIZE == 10, "Entry size mismatch"


def serialise(entries: list[tuple[int, int]], string_table: bytes) -> bytes:
    if len(entries) > 0xFFFF:
        raise ValueError(f"Too many entries: {len(entries)} (max 65535)")
    if len(string_table) > 0xFFFF:
        raise ValueError(f"String table too large: {len(string_table)} bytes (max 65535)")

    header = HEADER_STRUCT.pack(len(entries), len(string_table))
    body = bytearray()
    for digits_int, word_offset in entries:
        body += ENTRY_STRUCT.pack(digits_int, word_offset)

    return header + bytes(body) + string_table


# ── Emit C header -────

def emit_header(blob: bytes, entry_count: int, string_table_size: int,
                out_path: str) -> None:
    lines = [
        "// AUTO-GENERATED by gen_t9_dict.py — do not edit by hand",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define T9_ENTRY_COUNT       {entry_count}u",
        f"#define T9_STRING_TABLE_SIZE {string_table_size}u",
        f"#define T9_ENTRY_SIZE        10u   /* sizeof(uint64_t) + sizeof(uint16_t) */",
        f"#define T9_DATA_OFFSET_ENTRIES 4u  /* bytes after header */",
        f"#define T9_DATA_OFFSET_STRINGS ({4 + entry_count * 10}u)",
        "",
        "// Embed the entire binary as a byte array.",
        "// In firmware, place in DRAM or IRAM as needed.",
        f"static const uint8_t t9DictData[] = {{",
    ]

    # Emit as hex, 16 bytes per line
    hex_lines = []
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    lines += hex_lines
    lines += [
        "};",
        "",
        f"static const uint32_t t9DictSize = {len(blob)}u;",
        "",
    ]

    Path(out_path).write_text('\n'.join(lines) + '\n', encoding='utf-8')


# ── Verification -─────

def verify(entries: list[tuple[int, int]], string_table: bytes,
           words: list[str]) -> None:
    """Binary-search the entry list and assert known sequences resolve correctly."""

    def string_at(offset: int) -> str:
        end = string_table.index(0, offset)
        return string_table[offset:end].decode('ascii')

    def best_match(digit_str: str) -> str | None:
        key = digits_to_int(digit_str)
        lo, hi = 0, len(entries) - 1
        while lo <= hi:
            mid = (lo + hi) // 2
            if entries[mid][0] == key:
                # Walk back to first match in group
                while mid > 0 and entries[mid - 1][0] == key:
                    mid -= 1
                return string_at(entries[mid][1])
            elif entries[mid][0] < key:
                lo = mid + 1
            else:
                hi = mid - 1
        return None

    def all_matches(digit_str: str) -> list[str]:
        key = digits_to_int(digit_str)
        lo, hi = 0, len(entries) - 1
        first = -1
        while lo <= hi:
            mid = (lo + hi) // 2
            if entries[mid][0] == key:
                first = mid
                hi = mid - 1           # keep searching left for lower bound
            elif entries[mid][0] < key:
                lo = mid + 1
            else:
                hi = mid - 1
        if first == -1:
            return []
        results = []
        i = first
        while i < len(entries) and entries[i][0] == key:
            results.append(string_at(entries[i][1]))
            i += 1
        return results

    print("\n── Verification ─────────────────────────────────────")

    # Check every word in the list resolves to itself (or is the best match)
    # for its digit sequence — since it's frequency-ordered that's guaranteed
    # only for position-0 words in a collision group.
    miss = 0
    for rank, word in enumerate(words):
        digits = word_to_digits(word)
        if digits is None:
            continue
        result = best_match(digits)
        if result is None:
            print(f"  MISS  '{word}' ({digits}) → not found")
            miss += 1

    print(f"  All-words check: {len(words) - miss} found, {miss} missing")

    # Spot-check known sequences
    known = [
        ("843",     "the"),
        ("4663",    "good"),
        ("43556",   "hello"),
        ("9253",    "pale"),
        ("2665",    "cool"),
        ("7464",    "ring"),
    ]

    all_ok = True
    for digits, expected in known:
        got = best_match(digits)
        matches = all_matches(digits)
        status = "OK  " if got == expected else "WARN"
        if got != expected:
            all_ok = False
        print(f"  {status}  {digits} → '{got}'  "
              f"(expected '{expected}', group: {matches})")

    if all_ok:
        print("  ✓ All spot-checks passed")
    else:
        print("  ⚠  Some spot-checks did not match — expected word may not be "
              "in xxxx.txt or may rank lower than another collision.")

    print()


# ── Main -─────────────

def main():
    # Resolve paths relative to this script's location
    script_dir = Path(__file__).parent
    repo_root  = script_dir.parent

    wordlist_path = script_dir / "8293.txt"
    bin_out_path  = repo_root  / "src" / "t9_dict.bin"
    hdr_out_path  = repo_root  / "src" / "t9_dict.h"

    # Allow overrides via argv:  gen_t9_dict.py [wordlist] [bin_out] [hdr_out]
    if len(sys.argv) >= 2: wordlist_path = Path(sys.argv[1])
    if len(sys.argv) >= 3: bin_out_path  = Path(sys.argv[2])
    if len(sys.argv) >= 4: hdr_out_path  = Path(sys.argv[3])

    print(f"Reading word list: {wordlist_path}")
    if not wordlist_path.exists():
        print(f"ERROR: word list not found at {wordlist_path}", file=sys.stderr)
        sys.exit(1)

    words = load_words(str(wordlist_path))
    print(f"  Loaded {len(words)} unique words")

    print("Building entry table…")
    entries, string_table = build_entries(words)
    print(f"  {len(entries)} entries, {len(string_table)} bytes string table")

    blob = serialise(entries, string_table)
    print(f"  Binary size: {len(blob)} bytes  "
          f"({len(blob)/1024:.1f} KB)")

    bin_out_path.parent.mkdir(parents=True, exist_ok=True)
    bin_out_path.write_bytes(blob)
    print(f"  Written: {bin_out_path}")

    emit_header(blob, len(entries), len(string_table), str(hdr_out_path))
    print(f"  Written: {hdr_out_path}")

    verify(entries, string_table, words)


if __name__ == "__main__":
    main()