// AUTO-GENERATED by gen_t9_dict.py — do not edit by hand
#pragma once
#include <stdint.h>

#define T9_NODE_COUNT  20507u
#define T9_HEADER_SIZE 4u
#define T9_NODE_SIZE   8u

// The blob lives in src/t9_dict.cpp so the linker places it once, in Flash
// (.rodata), rather than duplicating it into every translation unit that
// includes this header.
extern const uint8_t  t9DictData[];
extern const uint32_t t9DictSize;
